[toolchain]
anchor_version = "1.0.1"
solana_version = "3.1.10"

[features]
seeds = false
skip-lint = false

[programs.localnet]
prophet = "3AUW4eLPigqyHmQNapcmv3JSYw6s8Aa5PPf87ayGT8kE"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
# Long timeout for warpSlot and integration tests
test = "yarn run test"

[test]
startup_wait = 30000 
shutdown_wait = 2000

[test.validator]
bind_address = "127.0.0.1"
gossip_host = "127.0.0.1"
dynamic_port_range = "10240-10255"
# url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899
