[tool.poetry]
name = "prophet-sdk"
version = "0.2.2"
description = "Python SDK for Prophet Prediction Markets"
authors = ["Prophet Protocol <dev@prophet.xyz>"]

[tool.poetry.dependencies]
python = "^3.9.6"
solana = "0.33.0"
solders = "0.21.0"
borsh-construct = "^0.1.0"
httpx = "0.28.1"

[tool.poetry.group.dev.dependencies]
pytest = {version = ">=9.0,<10", python = ">=3.10"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
