"""Immutable, independently-generated G1 admission cryptographic vectors."""
from __future__ import annotations

import base64
import hashlib
import zlib
from datetime import datetime, timezone

from src.signer_admission_grant import (
    AdmissionGrantContext,
    AdmissionIssuerKeyV1,
    GRANT_DOMAIN,
    GRANT_SCHEMA,
    GRANT_SIGNATURE_SCHEMA,
    REQUEST_BINDING_DOMAIN,
    admission_request_binding,
    parse_strict_signer_authorization_request,
    verify_admission_grant,
)


# Produced once by an independent RFC8785 implementation and deterministic
# test key.  These are literal frozen bytes, never generated by production.
VECTOR_SET = "PROPHET_SIGNER_ADMISSION_GRANT_CRYPTOGRAPHIC_VECTOR_SET_V1"
_RAW = "eNrtVEtT20gQ/i86Z6l5a2ZvgbJx8GK0RkDCRdXzsoVtSdYDI6f47xlB4jh79WFrt1J9kXq6v+n+pvv7GjVm6TYQ/Rkl85tkMkqz21Ga/jW6Hs3S7ONdOrmZf3r8mH66mWX3OPoQPbu6ycsixA9/Zt01rauzhStckzfZEpplOELiNAvIVV0uathkuQ145tJP8gsxXSzouBo/Pi92l6bZNRfztmJwnhC/7z7P/07yfTcLqRuoV64NaYo89JN5Lfa7l1rdnrcjN1VX5/vd9O4inY+7+4sFkffL4rFpt7P31nKfh24gg7Z1TQvtW6dfowr6dQl2+Dw6yQ7UhWKrpWvPfiD8cRR19jwQdZz2K4WHW986hWPPUeAZOkO/BG+qtdu44jukzRcBfmCen2bhjqdSf6/FeoQI00whTwRRQkjKJcQyFiiOhaGcCmUNV1JL7gjD3FrLifJaMeEw/7/NR+2ach1eILPO50X+RvyPhvBpFtDdc25dYdwBkpxm7xyV/oBHT7MBr9Pr3GR5UXXtz7dkp1nALbvWlBsXwL6MbodlMdsur50Na5htmmH832Yf1rnNuqLN1+9eiqLXD1GTLwpouzoQ516Cl2EiDVVYKiw4WEGFB7CMYBNLiSgLXo09jwUDEgYWIBaxZtIANR4D4pZiaRGApI5SbxDFRujgMCE89qAkAgrCYs60VTH1jEqpiApbAZx45H7ytHL9UOVD2lcl6b7Uu+vJFe/H491d8lmkhBdUJbvZbuXiak9Iwu7aoZ/Diut/T4X0qSp0+n7/VqHfKvQfViGFkJIUg1UcS0o8tjGVSDkcA7JSCmDOCgGcEuMc11oHxRKGC+aEZNJrJ7E1HjjSQXMwUQGJgRSOUeY1VpZSR5yRYS2cBqYJQwZjSpAiPsQi+08VIo/bJXnqJw/Tdvty2bP99VNuZvPxVowS4FfXq+XLNF319wnpr6LX12+C49yi"
_BINDING_JCS = "eNrtVttu4kgQ/Rc/70Z9d/e8JRlzCQthwCQzebHKfQEHsMGXEIjy79OEDMuORpqR0L5F9WK165zq7jp11C9BsbIl1FmRB58CaOpZUWY7m0Bukiqb5sFfQWnXja3q4NNLoBdNVdsymdrcVlmVzKCaeRgS54UvsoRybn2NQJH7bWdUit3muVTjqzqyPXVztdv0JtfxqNXcXU+JvJvlD1W9HnjcqiymJSyTzHisbrtOdi160yltrVoPT9NNW1eb6npUrxhcDYnbNV9HX4bZrtlDKz2zS/Cw4eh22IniZBzF8T9RPxrEyeUk7tyOug+Xcfd2kNxhn/5ky8xl/vCQQF37C3m/tJdgBdtFAWb/CXrdZKU1PiVZVp4bIw89yU+OVf3OVzNbX/zg/fsk6+IJ/wTzWdWhR/s//18f7FNmbK7tkZKcF57ysUgP7QHjECIsZQo5IogSQlIuIZShQGEoNOVUKKO5kqnkljDMjTGcKJcqJizmZ8ikaGpdLK0HfovG58nGQwt3vB56Xuz5mnSR6STLV039byfZefE2tlWx8LJJjHVZnr2p6Ac7Pi/20wCLzCRNXmeLg9ApOp2RQ7//s7JcLezS5u96Ntn0zVMCxM+L0xonQ3KBLlDwerzdud3u93gfb1cFab6Vm37nhm9brc1k+FXEhOdUDTeDzdyGqx0hQzap9wbh/Q/qpvTDYJ89nGEiNVVYKiw4GEGFAzCMYB1KiSjzqyl2PBQMiJcuQCjClEkNVDsMiBuKpUEAklpKnUYUa5H6Be3TQwdKIqAgDOYsNSqkjlEpFVF+PoATh+z+PMezph8u9OFCHy70exdK/8iFztfsH7sQeVjPyOO2c9+r18/tLdv1HzM9GLXWIhoCv+nPZ8+9eL69G5LtzS9cSCGkJMVgFMeSEodNSCVSFoeAjJQCmDVCAKdEW8vTNPWOJTQXzArJpEutxEY74Cj1noOJ8kwMpLCMMpdiZSi1xGrpB8SmwFLCkMaYEqSI87nIvLvQ0Qdef/WS6rYH0Si5/Nzvjsf7F9Qo+jKJxnFy1R187g7axxfVgQW/fgdseAHD"
_PREIMAGE = "eNrtVslu4zgQzXk+Q+eegLvIviVpeYnHjtqWne5cBIqLrdiWZC1x5CDn+e2hs7g9gwa6AWNuQV0Eqt4jWfXqgeH4JuwFUTzpd0fBOL74MuxPJv2bUTwOvk6DSRRf9kdf+qNuPINnf/9xdvbk5YUpZZ3mmffZk029yMt0Z2KZ6bhK55n3ySvNpjFV7X1+8tSqqWpTxnOTmSqt4oWsFg4G2GnhNlnLcmncHp5At21vXLLd9rEUk8s6MANxfbnbDqZX0bjTzK7miM8W2V1Vb0YOV5T5vJTrONUOq7q2l16xwXyOO0Xn7mG+7apqW12N64LIyxDZXfNt/DVMd80eWqmFWUsHC99rFkTRX8EwGEXxxTTq3Yz7dxfRvnYz6NIfTJna1F1exrKuXUHeivbkFbJd5VLvP6XaNGlptEuJ15XjhsBBj/Ljw67u5MXC1OfvvH8eZZ0/wP/AXFb12qP9n/+vD+Yh1SZT5kCJTgtHeZ8nr+2R2gKASEIEsIghwRjHlEuf+wz4PlOYYia0ooInnBpEINVaUyRsIggzkJ4gk7ypVb42Dvg9mJwmGwfN7aE8+LTY8zXJKlVxmhVN/aOT5LR4GdsqXznZxNrYNEtfVPTODk+L/TTIVarjJqvT1avQMTiekdd+/2tlXazM2mRvetbp/MVTPEBPi+M9jobkHJwD7/lQ3aVp92e8jdoiR833cjvsXdO209lOw28sQjTDItyOtkvjFzuEQjKt9wbh/E/WTemGwTw6OIGIKywgF5BRqRlmVkpNEFQ+5wATt5pAS31GJHLSldJnfkK4klhZKAHVGHINpOTYYGwVwFCxxC0ol+5bKTiQWDINKUm08LElmHOBhJsPSZEFZn+fw12TDxf6cKEPF/q1CyW/5UKna/a3XQjdbRbovu3dDurNY7clu+F9qkbjzoYFoaTXw+XicRAt21mI2uufuJAAQHAMpRYUcows1D7mQBjoS6A5Z5IYzZikGCljaJIkzrGYoowYxgm3ieFQKyspSJznQCQcE5GcGYKJTaDQGBtkFHcDYhJJEkSAghAjIJB1uUC/udDBB55/9pL69evTO2KBz/8AnmAPaw=="
_GRANT_JCS = "eNqNkcFuwjAMht+l51VK0gba3pCGGIcBArTDLpGTuBCtBJa0laZp776kHULaBXyyftuffyffCSiFlxasQuE6K4xOqkTeieQpAX0y3puzFQ4/O/St8EdgfBKmtVa8UCWtc1ZjLgtZ0zzTnDJVS15qOWWsxKIoMyk5ZwCQA8/YtC5KndMsh0BH2xt3tie0bQBeOtkYlWrsLbax2huN0bDHdjR8VVJCaGg4mMFOKMCDEYcc2D+cuhOhOxzfoRYQ/THCJikpUjbdU1plpCLk/driRuKYp3HPB36NWkgGwasjnqLZzXa9eZnvxW65WM23Yvb8utztluuVWGxnq714i6d5c7AB6s4NhonZTfHoehPeZECP2kDvoTFadLY1zT+r7Ga1Rxf/Mqnozy9cf6x0"
_GRANT_PREIMAGE = "eNqNkU1uwjAQhVGP0CNk3Ui2E0OSHVIRZVFAgLpgY/lnAlYTh9pJpKrq3WsnRUjd0FmN3rz5/Gxvd5vty+LA9qvlerFj8+fX1X6/2qzZcjdfH9gbnjw+TCZfEZcSLi03EpjtDNMqKiJxp6KniKtaO6cbwyx8dOBa5s6c0KnfVkrSTOa4TEkJqchEidNEUUxkKWiuxIyQHLIsT4SglHDOU04TMiuzXKU4Sbmng+m1bUwNpvXASycqLWMFvYE2THutIAR20I6Br0qMEPaGkx7i+AH/Z4Uly80vTt4p7/aX70AxHvIRRKYxymIyO2BcJKhA6Hi12JE49nE45x0+R803g+DkGeoQdnvvy4JZn4yH2qYCvzG/KQ5sr/2bDOhRG+g9r7RinWl19ScquUXtwYa/jAr8/QM64LaY"


def _frozen(value: str) -> bytes:
    return zlib.decompress(base64.b64decode(value))


def test_frozen_request_binding_vector_is_exact():
    request = parse_strict_signer_authorization_request(_frozen(_RAW))
    jcs, preimage, digest = admission_request_binding(request)
    assert jcs == _frozen(_BINDING_JCS)
    assert len(jcs) == 2695
    assert preimage == _frozen(_PREIMAGE)
    assert preimage == REQUEST_BINDING_DOMAIN + b"\x87\x0a\x00\x00" + jcs
    assert digest == "ddc58c91f42fe4b8bf143d512cfb59db7229e8893bb552aaa4a5327f89d4134a"


def test_frozen_signed_grant_vector_is_exact():
    request = parse_strict_signer_authorization_request(_frozen(_RAW))
    grant = {"schema": GRANT_SCHEMA, "version": 1, "grant_id": "c" * 32, "environment": "public-devnet", "git_sha": "a" * 40, "evidence_set_id": "evidence-001", "acceptance_run_id": "b" * 32, "signer_role": "A", "signer_service_id": "signer-a", "admission_request_sha256": "ddc58c91f42fe4b8bf143d512cfb59db7229e8893bb552aaa4a5327f89d4134a", "issuer_id": "issuer-a", "key_id": "key-a", "issued_at": "2026-08-27T11:30:00Z", "valid_until": "2026-08-27T12:30:00Z"}
    assert _frozen(_GRANT_JCS) == b'{"acceptance_run_id":"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb","admission_request_sha256":"ddc58c91f42fe4b8bf143d512cfb59db7229e8893bb552aaa4a5327f89d4134a","environment":"public-devnet","evidence_set_id":"evidence-001","git_sha":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","grant_id":"cccccccccccccccccccccccccccccccc","issued_at":"2026-08-27T11:30:00Z","issuer_id":"issuer-a","key_id":"key-a","schema":"PROPHET_SIGNER_ADMISSION_GRANT_V1","signer_role":"A","signer_service_id":"signer-a","valid_until":"2026-08-27T12:30:00Z","version":1}'
    preimage = _frozen(_GRANT_PREIMAGE)
    assert preimage == GRANT_DOMAIN + b"\x12\x02\x00\x00" + _frozen(_GRANT_JCS)
    assert hashlib.sha256(preimage).hexdigest() == "a2e34be0f9af3481a24d1b6de99861b877b1fa5405007823070be8dc686c39c3"
    envelope = {"schema": GRANT_SIGNATURE_SCHEMA, "version": 1, "algorithm": "ed25519", "issuer_id": "issuer-a", "key_id": "key-a", "signed_payload_sha256": "a2e34be0f9af3481a24d1b6de99861b877b1fa5405007823070be8dc686c39c3", "signature": "c9087242c65ba3b0f4bb3f8724082cbb8d0046f05c7181ec71d665ee38b760e7c4f90dbf5e285d1dba4723b76ae0807601b5d00bda9b6a989eafc426b12ab201"}
    context = AdmissionGrantContext("A", "signer-a", "public-devnet", "a" * 40, "evidence-001", "b" * 32)
    key = AdmissionIssuerKeyV1("key-a", "issuer-a", "A", "FAe4sisG95oZ42w7buUn5qEE4TAnfTTFPiguZUHmhiF", "2026-08-27T11:00:00Z", "2026-08-27T13:00:00Z")
    result = verify_admission_grant(unsigned_grant=grant, signature_envelope=envelope, request=request, context=context, issuer_keys=[key], trusted_now=datetime(2026, 8, 27, 12, 0, tzinfo=timezone.utc))
    assert result.grant_id == "c" * 32
