"""Pinned RFC 8785 dependency conformance proof for future P0C3E1 use.

Expected values are fixed RFC 8785 / ECMAScript serialization constants, never
generated by the dependency under test.
"""

from __future__ import annotations

import math

import pytest
import rfc8785


def test_rfc8785_fixed_reference_vectors() -> None:
    # RFC 8785 §3.2.3 property ordering uses UTF-16 code units.
    assert rfc8785.dumps(
        {
            "\u20ac": "Euro Sign",
            "\r": "Carriage Return",
            "\ufb33": "Hebrew Letter Dalet With Dagesh",
            "1": "One",
            "\U0001f600": "Emoji: Grinning Face",
            "\u0080": "Control",
            "\u00f6": "Latin Small Letter O With Diaeresis",
        }
    ) == (
        b'{"\\r":"Carriage Return","1":"One","\xc2\x80":"Control",'
        b'"\xc3\xb6":"Latin Small Letter O With Diaeresis","\xe2\x82\xac":"Euro Sign",'
        b'"\xf0\x9f\x98\x80":"Emoji: Grinning Face",'
        b'"\xef\xac\xb3":"Hebrew Letter Dalet With Dagesh"}'
    )
    assert rfc8785.dumps(
        {
            "nested": {"z": 1, "a": [3, 2, 1]},
            "empty_object": {},
            "empty_array": [],
            "empty_string": "",
        }
    ) == b'{"empty_array":[],"empty_object":{},"empty_string":"","nested":{"a":[3,2,1],"z":1}}'


def test_rfc8785_fixed_number_vectors() -> None:
    assert rfc8785.dumps(
        {"numbers": [333333333.33333329, 1e30, 4.50, 2e-3, 1e-27]}
    ) == b'{"numbers":[333333333.3333333,1e+30,4.5,0.002,1e-27]}'
    assert rfc8785.dumps(1e-6) == b"0.000001"
    assert rfc8785.dumps(1e-7) == b"1e-7"
    assert rfc8785.dumps(1e20) == b"100000000000000000000"
    assert rfc8785.dumps(1e21) == b"1e+21"
    assert rfc8785.dumps(-0.0) == b"0"
    assert rfc8785.dumps(9007199254740991) == b"9007199254740991"


def test_rfc8785_deterministic_byte_api_is_order_independent() -> None:
    first = {
        "schema": "PROPHET_OPERATED_SIGNER_TRUST_POLICY_V1",
        "version": 1,
        "environment": "public-devnet",
        "release_scope": ["51c5291f137df2f523a9f910c5d7e1d112f266e3"],
    }
    second = dict(reversed(list(first.items())))

    first_bytes = rfc8785.dumps(first)
    assert first_bytes == rfc8785.dumps(second)
    assert first_bytes == rfc8785.dumps(first)
    assert isinstance(first_bytes, bytes)
    assert first_bytes.decode("utf-8").encode("utf-8") == first_bytes


@pytest.mark.parametrize(
    "value",
    [
        math.nan,
        math.inf,
        -math.inf,
        b"bytes-are-not-json",
        object(),
        {1: "non-string-key"},
        9007199254740992,
    ],
)
def test_rfc8785_rejects_unsupported_or_non_i_json_inputs(value: object) -> None:
    with pytest.raises(rfc8785.CanonicalizationError):
        rfc8785.dumps(value)


def test_p0c3e1_security_relevant_schema_has_no_float_fields() -> None:
    # P0C3E1's proposed numbers are schema/version fields and integer lengths;
    # all security bindings, timestamps, digests, and identifiers are strings.
    security_relevant_float_fields: tuple[str, ...] = ()
    assert security_relevant_float_fields == ()
